[package]
name = "voting-dapp"
version = "1.0.0"
authors = []

[addresses]
TutoringDao = "0x001"
my_addrx = "0x001"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
[dev-dependencies]